name: Publish to Pypi

on:
    push:
        tags:
            - "v*.*.*"

jobs:
    publish_pypi:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
            - name: Install dependencies
              run: pip install .
            - name: Builds and uploads to PyPI
              run: |
                  python3 setup.py sdist bdist_wheel
                  python3 -m twine upload dist/*
              env:
                  TWINE_USERNAME: __token__
                  TWINE_PASSWORD: ${{ secrets.PIPY_PASSWORD }}
